### ISSUE TITLE
Ap1le_carheist

### ISSUE THREAD

**Issue by Ap1leDK** [LAB-ProductionsDK/LabProductionsRoadmap#8]
# Ap1le_Carheist
## Roadmap

>FXmanifest
- [x] Add dependencies

> Create Starting Ped

- [x] Create Ped at position
- [ ] Make Ped trigger 2 different events (**Start the heist** and **Start the cooldown**)
- [ ] Take money on start

> Reward

- Bad car
- [ ] Add the cars
- [ ] Add the max price

- Mid car
- [ ] Add the cars
- [ ] Add the max price 

- High car
- [ ] Add the cars
- [ ] Add the max price   

> Reward

- [ ] Take the state of the car (health) and do some math to minus it form the max value

**Comment by Ap1leDK** [comment]
When Spawning the vehicle/after going thru the takemoney bit, the car spawn no matter what. Even if you dont have enough money
